-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, (S.TOTAL_SALES * P.PRICE) AS SALES
FROM (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS TOTAL_SALES
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) AS S
JOIN PRODUCT P ON S.PRODUCT_ID = P.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE;